---
title: Raul Tizze
include: ['_pages']
exclude: ['_includes/notes_graph.json']
baseurl: ''
use_html_extension: false
open_external_links_in_new_tab: true
embed_tweets: false
permalink: pretty
relative_permalinks: false

plugins:
  - jekyll-last-modified-at

sass:
  sass_dir: _sass
  style: :compressed

collections:
  notes:
    output: true
    permalink: /:slug

defaults:
  - scope:
      path: "**/*"
    values:
      layout: "default"
  - scope:
      path: "_notes/**/*.md"
    values:
      layout: "note"
---

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>{{ page.title }}</title>
    <style>
      body {
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
        margin: 0;
        padding: 0;
      }
      .container {
        text-align: center;
      }
      h1 {
        margin-top: 0;
        margin-bottom: 0;
      }
      .black-bg {
        background-color: black;
      }
    </style>
  </head>
  <body class="black-bg">
    <div class="container">
      <h1>{{ page.title }}</h1>
      {% include header.html %}
      {{ content }}
      {% include footer.html %}
    </div>
  </body>
</html>